// Generated by Bisonc++ V5.02.00 on Fri, 07 Apr 2017 00:09:12 +0200

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {294, 1}, // 1: start ->  program
     {295, 3}, // 2: program ->  header declarations body
     {296, 2}, // 3: header (PROGRAM) ->  PROGRAM IDENTIFIER
     {297, 0}, // 4: declarations ->  <empty>
     {297, 2}, // 5: declarations ->  declaration declarations
     {299, 3}, // 6: declaration (IDENTIFIER) ->  type IDENTIFIER SEMICOLON
     {300, 1}, // 7: type (NATURAL) ->  NATURAL
     {300, 1}, // 8: type (BOOLEAN) ->  BOOLEAN
     {298, 3}, // 9: body (TBEGIN) ->  TBEGIN statements END
     {301, 1}, // 10: statements ->  statement
     {301, 2}, // 11: statements ->  statement statements
     {302, 1}, // 12: statement ->  skip
     {302, 1}, // 13: statement ->  assignment
     {302, 1}, // 14: statement ->  write
     {302, 1}, // 15: statement ->  read
     {302, 1}, // 16: statement ->  while_loop
     {302, 1}, // 17: statement ->  for_loop
     {302, 1}, // 18: statement ->  conditional
     {303, 2}, // 19: skip (SKIP) ->  SKIP SEMICOLON
     {304, 4}, // 20: assignment (IDENTIFIER) ->  IDENTIFIER ASSIGN expr SEMICOLON
     {305, 5}, // 21: write (WRITE) ->  WRITE LEFT_BRACKET expr RIGHT_BRACKET SEMICOLON
     {306, 5}, // 22: read (READ) ->  READ LEFT_BRACKET IDENTIFIER RIGHT_BRACKET SEMICOLON
     {307, 5}, // 23: while_loop (WHILE) ->  WHILE expr DO statements DONE
     {308, 9}, // 24: for_loop (FOR) ->  FOR IDENTIFIER IN expr RANGE expr DO statements DONE
     {309, 5}, // 25: conditional (IF) ->  IF expr THEN statements ENDIF
     {309, 7}, // 26: conditional (IF) ->  IF expr THEN statements ELSE statements ENDIF
     {310, 1}, // 27: expr (TRUE) ->  TRUE
     {310, 1}, // 28: expr (FALSE) ->  FALSE
     {310, 1}, // 29: expr (NATURAL_LITERAL) ->  NATURAL_LITERAL
     {310, 1}, // 30: expr (IDENTIFIER) ->  IDENTIFIER
     {310, 3}, // 31: expr (EQUALS) ->  expr EQUALS expr
     {310, 3}, // 32: expr (LEFT_BRACKET) ->  LEFT_BRACKET expr RIGHT_BRACKET
     {310, 2}, // 33: expr (NOT) ->  NOT expr
     {310, 3}, // 34: expr (AND) ->  expr AND expr
     {310, 3}, // 35: expr (OR) ->  expr OR expr
     {310, 3}, // 36: expr (LESS_THAN) ->  expr LESS_THAN expr
     {310, 3}, // 37: expr (GREATER_THAN) ->  expr GREATER_THAN expr
     {310, 3}, // 38: expr (PLUS) ->  expr PLUS expr
     {310, 3}, // 39: expr (MINUS) ->  expr MINUS expr
     {310, 3}, // 40: expr (ASTERIKS) ->  expr ASTERIKS expr
     {310, 3}, // 41: expr (MOD) ->  expr MOD expr
     {310, 3}, // 42: expr (DIV) ->  expr DIV expr
     {311, 1}, // 43: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 5} },           
    { {       294}, { 1} }, // start  
    { {       295}, { 2} }, // program
    { {       296}, { 3} }, // header 
    { {       257}, { 4} }, // PROGRAM
    { {         0}, { 0} },           
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  6} },                
    { {     297}, {  5} }, // declarations
    { {     299}, {  6} }, // declaration 
    { {     300}, {  7} }, // type        
    { {     261}, {  8} }, // NATURAL     
    { {     262}, {  9} }, // BOOLEAN     
    { {       0}, { -4} },                
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       283}, { 10} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       298}, { 11} }, // body  
    { {       258}, { 12} }, // TBEGIN
    { {         0}, {  0} },          
};

SR__ s_6[] =
{
    { { REQ_DEF}, {  6} },                
    { {     297}, { 13} }, // declarations
    { {     299}, {  6} }, // declaration 
    { {     300}, {  7} }, // type        
    { {     261}, {  8} }, // NATURAL     
    { {     262}, {  9} }, // BOOLEAN     
    { {       0}, { -4} },                
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       283}, { 14} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_11[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, { 17} },               
    { {       301}, { 15} }, // statements 
    { {       302}, { 16} }, // statement  
    { {       303}, { 17} }, // skip       
    { {       304}, { 18} }, // assignment 
    { {       305}, { 19} }, // write      
    { {       306}, { 20} }, // read       
    { {       307}, { 21} }, // while_loop 
    { {       308}, { 22} }, // for_loop   
    { {       309}, { 23} }, // conditional
    { {       259}, { 24} }, // SKIP       
    { {       283}, { 25} }, // IDENTIFIER 
    { {       277}, { 26} }, // WRITE      
    { {       276}, { 27} }, // READ       
    { {       270}, { 28} }, // WHILE      
    { {       271}, { 29} }, // FOR        
    { {       266}, { 30} }, // IF         
    { {         0}, {  0} },               
};

SR__ s_13[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       281}, { 31} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       260}, { 32} }, // END
    { {         0}, {  0} },       
};

SR__ s_16[] =
{
    { { REQ_DEF}, {  17} },               
    { {     301}, {  33} }, // statements 
    { {     302}, {  16} }, // statement  
    { {     303}, {  17} }, // skip       
    { {     304}, {  18} }, // assignment 
    { {     305}, {  19} }, // write      
    { {     306}, {  20} }, // read       
    { {     307}, {  21} }, // while_loop 
    { {     308}, {  22} }, // for_loop   
    { {     309}, {  23} }, // conditional
    { {     259}, {  24} }, // SKIP       
    { {     283}, {  25} }, // IDENTIFIER 
    { {     277}, {  26} }, // WRITE      
    { {     276}, {  27} }, // READ       
    { {     270}, {  28} }, // WHILE      
    { {     271}, {  29} }, // FOR        
    { {     266}, {  30} }, // IF         
    { {       0}, { -10} },               
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       281}, { 34} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       280}, { 35} }, // ASSIGN
    { {         0}, {  0} },          
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       278}, { 36} }, // LEFT_BRACKET
    { {         0}, {  0} },                
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       278}, { 37} }, // LEFT_BRACKET
    { {         0}, {  0} },                
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 38} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       283}, { 45} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 46} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_31[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 47} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 48} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       283}, { 49} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       274}, { 50} }, // DO          
    { {       286}, { 51} }, // EQUALS      
    { {       284}, { 52} }, // AND         
    { {       285}, { 53} }, // OR          
    { {       287}, { 54} }, // LESS_THAN   
    { {       288}, { 55} }, // GREATER_THAN
    { {       289}, { 56} }, // PLUS        
    { {       290}, { 57} }, // MINUS       
    { {       291}, { 58} }, // ASTERIKS    
    { {       293}, { 59} }, // MOD         
    { {       292}, { 60} }, // DIV         
    { {         0}, {  0} },                
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 61} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 62} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       272}, { 63} }, // IN
    { {         0}, {  0} },      
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       267}, { 64} }, // THEN        
    { {       286}, { 51} }, // EQUALS      
    { {       284}, { 52} }, // AND         
    { {       285}, { 53} }, // OR          
    { {       287}, { 54} }, // LESS_THAN   
    { {       288}, { 55} }, // GREATER_THAN
    { {       289}, { 56} }, // PLUS        
    { {       290}, { 57} }, // MINUS       
    { {       291}, { 58} }, // ASTERIKS    
    { {       293}, { 59} }, // MOD         
    { {       292}, { 60} }, // DIV         
    { {         0}, {  0} },                
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       281}, { 65} }, // SEMICOLON   
    { {       286}, { 51} }, // EQUALS      
    { {       284}, { 52} }, // AND         
    { {       285}, { 53} }, // OR          
    { {       287}, { 54} }, // LESS_THAN   
    { {       288}, { 55} }, // GREATER_THAN
    { {       289}, { 56} }, // PLUS        
    { {       290}, { 57} }, // MINUS       
    { {       291}, { 58} }, // ASTERIKS    
    { {       293}, { 59} }, // MOD         
    { {       292}, { 60} }, // DIV         
    { {         0}, {  0} },                
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, { 12} },                 
    { {       279}, { 66} }, // RIGHT_BRACKET
    { {       286}, { 51} }, // EQUALS       
    { {       284}, { 52} }, // AND          
    { {       285}, { 53} }, // OR           
    { {       287}, { 54} }, // LESS_THAN    
    { {       288}, { 55} }, // GREATER_THAN 
    { {       289}, { 56} }, // PLUS         
    { {       290}, { 57} }, // MINUS        
    { {       291}, { 58} }, // ASTERIKS     
    { {       293}, { 59} }, // MOD          
    { {       292}, { 60} }, // DIV          
    { {         0}, {  0} },                 
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  2} },                 
    { {       279}, { 67} }, // RIGHT_BRACKET
    { {         0}, {  0} },                 
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, { 17} },               
    { {       301}, { 68} }, // statements 
    { {       302}, { 16} }, // statement  
    { {       303}, { 17} }, // skip       
    { {       304}, { 18} }, // assignment 
    { {       305}, { 19} }, // write      
    { {       306}, { 20} }, // read       
    { {       307}, { 21} }, // while_loop 
    { {       308}, { 22} }, // for_loop   
    { {       309}, { 23} }, // conditional
    { {       259}, { 24} }, // SKIP       
    { {       283}, { 25} }, // IDENTIFIER 
    { {       277}, { 26} }, // WRITE      
    { {       276}, { 27} }, // READ       
    { {       270}, { 28} }, // WHILE      
    { {       271}, { 29} }, // FOR        
    { {       266}, { 30} }, // IF         
    { {         0}, {  0} },               
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 69} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 70} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 71} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 72} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 73} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 74} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 75} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 76} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 77} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 78} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, { 12} },                 
    { {       279}, { 79} }, // RIGHT_BRACKET
    { {       286}, { 51} }, // EQUALS       
    { {       284}, { 52} }, // AND          
    { {       285}, { 53} }, // OR           
    { {       287}, { 54} }, // LESS_THAN    
    { {       288}, { 55} }, // GREATER_THAN 
    { {       289}, { 56} }, // PLUS         
    { {       290}, { 57} }, // MINUS        
    { {       291}, { 58} }, // ASTERIKS     
    { {       293}, { 59} }, // MOD          
    { {       292}, { 60} }, // DIV          
    { {         0}, {  0} },                 
};

SR__ s_62[] =
{
    { { REQ_DEF}, {  11} },                
    { {     286}, {  51} }, // EQUALS      
    { {     284}, {  52} }, // AND         
    { {     285}, {  53} }, // OR          
    { {     287}, {  54} }, // LESS_THAN   
    { {     288}, {  55} }, // GREATER_THAN
    { {     289}, {  56} }, // PLUS        
    { {     290}, {  57} }, // MINUS       
    { {     291}, {  58} }, // ASTERIKS    
    { {     293}, {  59} }, // MOD         
    { {     292}, {  60} }, // DIV         
    { {       0}, { -33} },                
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 80} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, { 17} },               
    { {       301}, { 81} }, // statements 
    { {       302}, { 16} }, // statement  
    { {       303}, { 17} }, // skip       
    { {       304}, { 18} }, // assignment 
    { {       305}, { 19} }, // write      
    { {       306}, { 20} }, // read       
    { {       307}, { 21} }, // while_loop 
    { {       308}, { 22} }, // for_loop   
    { {       309}, { 23} }, // conditional
    { {       259}, { 24} }, // SKIP       
    { {       283}, { 25} }, // IDENTIFIER 
    { {       277}, { 26} }, // WRITE      
    { {       276}, { 27} }, // READ       
    { {       270}, { 28} }, // WHILE      
    { {       271}, { 29} }, // FOR        
    { {       266}, { 30} }, // IF         
    { {         0}, {  0} },               
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       281}, { 82} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       281}, { 83} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       275}, { 84} }, // DONE
    { {         0}, {  0} },        
};

SR__ s_69[] =
{
    { { REQ_DEF}, {   8} },                
    { {     287}, {  54} }, // LESS_THAN   
    { {     288}, {  55} }, // GREATER_THAN
    { {     289}, {  56} }, // PLUS        
    { {     290}, {  57} }, // MINUS       
    { {     291}, {  58} }, // ASTERIKS    
    { {     293}, {  59} }, // MOD         
    { {     292}, {  60} }, // DIV         
    { {       0}, { -31} },                
};

SR__ s_70[] =
{
    { { REQ_DEF}, {   9} },                
    { {     286}, {  51} }, // EQUALS      
    { {     287}, {  54} }, // LESS_THAN   
    { {     288}, {  55} }, // GREATER_THAN
    { {     289}, {  56} }, // PLUS        
    { {     290}, {  57} }, // MINUS       
    { {     291}, {  58} }, // ASTERIKS    
    { {     293}, {  59} }, // MOD         
    { {     292}, {  60} }, // DIV         
    { {       0}, { -34} },                
};

SR__ s_71[] =
{
    { { REQ_DEF}, {   9} },                
    { {     286}, {  51} }, // EQUALS      
    { {     287}, {  54} }, // LESS_THAN   
    { {     288}, {  55} }, // GREATER_THAN
    { {     289}, {  56} }, // PLUS        
    { {     290}, {  57} }, // MINUS       
    { {     291}, {  58} }, // ASTERIKS    
    { {     293}, {  59} }, // MOD         
    { {     292}, {  60} }, // DIV         
    { {       0}, { -35} },                
};

SR__ s_72[] =
{
    { { REQ_DEF}, {   6} },            
    { {     289}, {  56} }, // PLUS    
    { {     290}, {  57} }, // MINUS   
    { {     291}, {  58} }, // ASTERIKS
    { {     293}, {  59} }, // MOD     
    { {     292}, {  60} }, // DIV     
    { {       0}, { -36} },            
};

SR__ s_73[] =
{
    { { REQ_DEF}, {   6} },            
    { {     289}, {  56} }, // PLUS    
    { {     290}, {  57} }, // MINUS   
    { {     291}, {  58} }, // ASTERIKS
    { {     293}, {  59} }, // MOD     
    { {     292}, {  60} }, // DIV     
    { {       0}, { -37} },            
};

SR__ s_74[] =
{
    { { REQ_DEF}, {   4} },            
    { {     291}, {  58} }, // ASTERIKS
    { {     293}, {  59} }, // MOD     
    { {     292}, {  60} }, // DIV     
    { {       0}, { -38} },            
};

SR__ s_75[] =
{
    { { REQ_DEF}, {   4} },            
    { {     291}, {  58} }, // ASTERIKS
    { {     293}, {  59} }, // MOD     
    { {     292}, {  60} }, // DIV     
    { {       0}, { -39} },            
};

SR__ s_76[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_77[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_78[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       273}, { 85} }, // RANGE       
    { {       286}, { 51} }, // EQUALS      
    { {       284}, { 52} }, // AND         
    { {       285}, { 53} }, // OR          
    { {       287}, { 54} }, // LESS_THAN   
    { {       288}, { 55} }, // GREATER_THAN
    { {       289}, { 56} }, // PLUS        
    { {       290}, { 57} }, // MINUS       
    { {       291}, { 58} }, // ASTERIKS    
    { {       293}, { 59} }, // MOD         
    { {       292}, { 60} }, // DIV         
    { {         0}, {  0} },                
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       269}, { 86} }, // ENDIF
    { {       268}, { 87} }, // ELSE 
    { {         0}, {  0} },         
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       310}, { 88} }, // expr           
    { {       263}, { 39} }, // TRUE           
    { {       264}, { 40} }, // FALSE          
    { {       282}, { 41} }, // NATURAL_LITERAL
    { {       283}, { 42} }, // IDENTIFIER     
    { {       278}, { 43} }, // LEFT_BRACKET   
    { {       265}, { 44} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, { 17} },               
    { {       301}, { 89} }, // statements 
    { {       302}, { 16} }, // statement  
    { {       303}, { 17} }, // skip       
    { {       304}, { 18} }, // assignment 
    { {       305}, { 19} }, // write      
    { {       306}, { 20} }, // read       
    { {       307}, { 21} }, // while_loop 
    { {       308}, { 22} }, // for_loop   
    { {       309}, { 23} }, // conditional
    { {       259}, { 24} }, // SKIP       
    { {       283}, { 25} }, // IDENTIFIER 
    { {       277}, { 26} }, // WRITE      
    { {       276}, { 27} }, // READ       
    { {       270}, { 28} }, // WHILE      
    { {       271}, { 29} }, // FOR        
    { {       266}, { 30} }, // IF         
    { {         0}, {  0} },               
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       274}, { 90} }, // DO          
    { {       286}, { 51} }, // EQUALS      
    { {       284}, { 52} }, // AND         
    { {       285}, { 53} }, // OR          
    { {       287}, { 54} }, // LESS_THAN   
    { {       288}, { 55} }, // GREATER_THAN
    { {       289}, { 56} }, // PLUS        
    { {       290}, { 57} }, // MINUS       
    { {       291}, { 58} }, // ASTERIKS    
    { {       293}, { 59} }, // MOD         
    { {       292}, { 60} }, // DIV         
    { {         0}, {  0} },                
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       269}, { 91} }, // ENDIF
    { {         0}, {  0} },         
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, { 17} },               
    { {       301}, { 92} }, // statements 
    { {       302}, { 16} }, // statement  
    { {       303}, { 17} }, // skip       
    { {       304}, { 18} }, // assignment 
    { {       305}, { 19} }, // write      
    { {       306}, { 20} }, // read       
    { {       307}, { 21} }, // while_loop 
    { {       308}, { 22} }, // for_loop   
    { {       309}, { 23} }, // conditional
    { {       259}, { 24} }, // SKIP       
    { {       283}, { 25} }, // IDENTIFIER 
    { {       277}, { 26} }, // WRITE      
    { {       276}, { 27} }, // READ       
    { {       270}, { 28} }, // WHILE      
    { {       271}, { 29} }, // FOR        
    { {       266}, { 30} }, // IF         
    { {         0}, {  0} },               
};

SR__ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       275}, { 93} }, // DONE
    { {         0}, {  0} },        
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,
};

} // anonymous namespace ends




// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void ParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack__.size();
    if (static_cast<size_t>(d_stackIdx__ + 1) == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
        if (d_valueStack__.capacity() >= newSize)
            d_valueStack__.resize(newSize);
        else
        {
            std::vector<STYPE__> enlarged(newSize);
            for (size_t idx = 0; idx != currentSize; ++idx)
                enlarged[idx] = std::move(d_valueStack__[idx]);
            d_valueStack__.swap(enlarged);
        }
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = std::move(d_val__);
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = std::move(d_nextVal__);
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = std::move(d_val__);
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 26 "parse-while.y"
        {
         std::cout << "start -> program" << std::endl;
         }
        break;

        case 2:
#line 32 "parse-while.y"
        {
         std::cout << "program -> header declarations body" << std::endl;
         }
        break;

        case 3:
#line 38 "parse-while.y"
        {
         std::cout << "header -> PROGRAM IDENTIFIER" << std::endl;
         }
        break;

        case 4:
#line 45 "parse-while.y"
        {
         std::cout << "declarations -> \"\"" << std::endl;
         }
        break;

        case 5:
#line 49 "parse-while.y"
        {
         std::cout << "declarations -> declaration declarations" << std::endl;
         }
        break;

        case 6:
#line 55 "parse-while.y"
        {
         std::cout << "declaration -> type IDENTIFIER SEMICOLON" << std::endl;
         }
        break;

        case 7:
#line 62 "parse-while.y"
        {
         std::cout << "type -> NATURAL" << std::endl;
         }
        break;

        case 8:
#line 66 "parse-while.y"
        {
         std::cout << "type -> BOOLEAN" << std::endl;
         }
        break;

        case 9:
#line 72 "parse-while.y"
        {
         std::cout << "body -> TBEGIN statements END" << std::endl;
         }
        break;

        case 10:
#line 79 "parse-while.y"
        {
         std::cout << "statements -> statement" << std::endl;
         }
        break;

        case 11:
#line 83 "parse-while.y"
        {
         std::cout << "statements -> statement statements" << std::endl;
         }
        break;

        case 12:
#line 90 "parse-while.y"
        {
         std::cout << "statement -> skip" << std::endl;
         }
        break;

        case 13:
#line 94 "parse-while.y"
        {
         std::cout << "statement -> assignment" << std::endl;
         }
        break;

        case 14:
#line 98 "parse-while.y"
        {
         std::cout << "statement -> write" << std::endl;
         }
        break;

        case 15:
#line 102 "parse-while.y"
        {
         std::cout << "statement -> read" << std::endl;
         }
        break;

        case 16:
#line 106 "parse-while.y"
        {
         std::cout << "statement -> while_loop" << std::endl;
         }
        break;

        case 17:
#line 110 "parse-while.y"
        {
         std::cout << "statement -> for_loop" << std::endl;
         }
        break;

        case 18:
#line 114 "parse-while.y"
        {
         std::cout << "statement -> conditional" << std::endl;
         }
        break;

        case 19:
#line 120 "parse-while.y"
        {
         std::cout << "skip -> SKIP SEMICOLON" << std::endl;
         }
        break;

        case 20:
#line 126 "parse-while.y"
        {
         std::cout << "assignment -> IDENTIFIER ASSIGN expr" << std::endl;
         }
        break;

        case 21:
#line 132 "parse-while.y"
        {
         std::cout << "write -> WRITE LEFT_BRACKET expr RIGHT_BRACKET SEMICOLON" << std::endl;
         }
        break;

        case 22:
#line 138 "parse-while.y"
        {
         std::cout << "read -> READ LEFT_BRACKET IDENTIFIER RIGHT_BRACKET SEMICOLON" << std::endl;
         }
        break;

        case 23:
#line 144 "parse-while.y"
        {
         std::cout << "while_loop -> WHILE expr DO statements DONE" << std::endl;
         }
        break;

        case 24:
#line 150 "parse-while.y"
        {
         std::cout << "for_loop -> FOR IDENTIFIER IN expr RANGE expr DO statements DONE" << std::endl;
         }
        break;

        case 25:
#line 157 "parse-while.y"
        {
         std::cout << "conditional -> IF expr THEN statements ENDIF" << std::endl;
         }
        break;

        case 26:
#line 161 "parse-while.y"
        {
         std::cout << "conditional -> IF expr THEN statements ELSE statements ENDIF" << std::endl;
         }
        break;

        case 27:
#line 168 "parse-while.y"
        {
         std::cout << "expr -> TRUE" << std::endl;
         }
        break;

        case 28:
#line 172 "parse-while.y"
        {
         std::cout << "expr -> FALSE" << std::endl;
         }
        break;

        case 29:
#line 176 "parse-while.y"
        {
         std::cout << "expr -> NATURAL_LITERAL" << std::endl;
         }
        break;

        case 30:
#line 180 "parse-while.y"
        {
         std::cout << "expr -> IDENTIFIER" << std::endl;
         }
        break;

        case 31:
#line 184 "parse-while.y"
        {
         std::cout << "expr -> expr EQUALS expr" << std::endl;
         }
        break;

        case 32:
#line 188 "parse-while.y"
        {
         std::cout << "expr -> LEFT_BRACKET expr RIGHT_BRACKET" << std::endl;
         }
        break;

        case 33:
#line 192 "parse-while.y"
        {
         std::cout << "expr -> NOT expr" << std::endl;
         }
        break;

        case 34:
#line 196 "parse-while.y"
        {
         std::cout << "expr -> expr AND expr" << std::endl;
         }
        break;

        case 35:
#line 200 "parse-while.y"
        {
         std::cout << "expr -> expr OR expr" << std::endl;
         }
        break;

        case 36:
#line 204 "parse-while.y"
        {
         std::cout << "expr -> expr LESS_THAN expr" << std::endl;
         }
        break;

        case 37:
#line 208 "parse-while.y"
        {
         std::cout << "expr -> expr GREATER_THAN expr" << std::endl;
         }
        break;

        case 38:
#line 212 "parse-while.y"
        {
         std::cout << "expr -> expr PLUS expr" << std::endl;
         }
        break;

        case 39:
#line 216 "parse-while.y"
        {
         std::cout << "expr -> expr MINUS expr" << std::endl;
         }
        break;

        case 40:
#line 220 "parse-while.y"
        {
         std::cout << "expr -> expr ASTERIKS expr" << std::endl;
         }
        break;

        case 41:
#line 224 "parse-while.y"
        {
         std::cout << "expr -> expr MOD expr" << std::endl;
         }
        break;

        case 42:
#line 228 "parse-while.y"
        {
         std::cout << "expr -> expr DIV expr" << std::endl;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



