// Generated by Bisonc++ V4.09.02 on Fri, 19 May 2017 18:22:49 +0200

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {306, 1}, // 1: start ->  program
     {307, 3}, // 2: program ->  header declarations body
     {308, 2}, // 3: header (PROGRAM) ->  PROGRAM IDENTIFIER
     {309, 0}, // 4: declarations ->  <empty>
     {309, 2}, // 5: declarations ->  declaration declarations
     {310, 3}, // 6: declaration (NATURAL) ->  NATURAL IDENTIFIER SEMICOLON
     {310, 3}, // 7: declaration (BOOLEAN) ->  BOOLEAN IDENTIFIER SEMICOLON
     {311, 3}, // 8: body (TBEGIN) ->  TBEGIN statements END
     {312, 1}, // 9: statements ->  statement
     {312, 2}, // 10: statements ->  statement statements
     {313, 1}, // 11: statement ->  skip
     {313, 1}, // 12: statement ->  assignment
     {313, 1}, // 13: statement ->  write
     {313, 1}, // 14: statement ->  read
     {313, 1}, // 15: statement ->  while_loop
     {313, 1}, // 16: statement ->  for_loop
     {313, 1}, // 17: statement ->  conditional
     {314, 2}, // 18: skip (SKIP) ->  SKIP SEMICOLON
     {315, 4}, // 19: assignment (IDENTIFIER) ->  IDENTIFIER ASSIGN expr SEMICOLON
     {316, 5}, // 20: write (WRITE) ->  WRITE LEFT_BRACKET expr RIGHT_BRACKET SEMICOLON
     {317, 5}, // 21: read (READ) ->  READ LEFT_BRACKET IDENTIFIER RIGHT_BRACKET SEMICOLON
     {318, 5}, // 22: while_loop (WHILE) ->  WHILE expr DO statements DONE
     {319, 9}, // 23: for_loop (FOR) ->  FOR IDENTIFIER IN expr RANGE expr DO statements DONE
     {320, 5}, // 24: conditional (IF) ->  IF expr THEN statements ENDIF
     {320, 7}, // 25: conditional (IF) ->  IF expr THEN statements ELSE statements ENDIF
     {321, 1}, // 26: expr (TRUE) ->  TRUE
     {321, 1}, // 27: expr (FALSE) ->  FALSE
     {321, 1}, // 28: expr (NATURAL_LITERAL) ->  NATURAL_LITERAL
     {321, 1}, // 29: expr (IDENTIFIER) ->  IDENTIFIER
     {321, 3}, // 30: expr (EQUALS) ->  expr EQUALS expr
     {321, 3}, // 31: expr (LEFT_BRACKET) ->  LEFT_BRACKET expr RIGHT_BRACKET
     {321, 2}, // 32: expr (NOT) ->  NOT expr
     {321, 3}, // 33: expr (AND) ->  expr AND expr
     {321, 3}, // 34: expr (OR) ->  expr OR expr
     {321, 3}, // 35: expr (LESS_THAN) ->  expr LESS_THAN expr
     {321, 3}, // 36: expr (GREATER_THAN) ->  expr GREATER_THAN expr
     {321, 3}, // 37: expr (PLUS) ->  expr PLUS expr
     {321, 3}, // 38: expr (MINUS) ->  expr MINUS expr
     {321, 3}, // 39: expr (ASTERIKS) ->  expr ASTERIKS expr
     {321, 3}, // 40: expr (MOD) ->  expr MOD expr
     {321, 3}, // 41: expr (DIV) ->  expr DIV expr
     {322, 1}, // 42: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 5} },           
    { {       306}, { 1} }, // start  
    { {       307}, { 2} }, // program
    { {       308}, { 3} }, // header 
    { {       257}, { 4} }, // PROGRAM
    { {         0}, { 0} },           
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  5} },                
    { {     309}, {  5} }, // declarations
    { {     310}, {  6} }, // declaration 
    { {     261}, {  7} }, // NATURAL     
    { {     262}, {  8} }, // BOOLEAN     
    { {       0}, { -4} },                
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, { 2} },              
    { {       282}, { 9} }, // IDENTIFIER
    { {         0}, { 0} },              
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       311}, { 10} }, // body  
    { {       258}, { 11} }, // TBEGIN
    { {         0}, {  0} },          
};

SR__ s_6[] =
{
    { { REQ_DEF}, {  5} },                
    { {     309}, { 12} }, // declarations
    { {     310}, {  6} }, // declaration 
    { {     261}, {  7} }, // NATURAL     
    { {     262}, {  8} }, // BOOLEAN     
    { {       0}, { -4} },                
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       282}, { 13} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       282}, { 14} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, { 17} },               
    { {       312}, { 15} }, // statements 
    { {       313}, { 16} }, // statement  
    { {       314}, { 17} }, // skip       
    { {       315}, { 18} }, // assignment 
    { {       316}, { 19} }, // write      
    { {       317}, { 20} }, // read       
    { {       318}, { 21} }, // while_loop 
    { {       319}, { 22} }, // for_loop   
    { {       320}, { 23} }, // conditional
    { {       259}, { 24} }, // SKIP       
    { {       282}, { 25} }, // IDENTIFIER 
    { {       277}, { 26} }, // WRITE      
    { {       276}, { 27} }, // READ       
    { {       270}, { 28} }, // WHILE      
    { {       271}, { 29} }, // FOR        
    { {       266}, { 30} }, // IF         
    { {         0}, {  0} },               
};

SR__ s_12[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       281}, { 31} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       281}, { 32} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       260}, { 33} }, // END
    { {         0}, {  0} },       
};

SR__ s_16[] =
{
    { { REQ_DEF}, { 17} },               
    { {     312}, { 34} }, // statements 
    { {     313}, { 16} }, // statement  
    { {     314}, { 17} }, // skip       
    { {     315}, { 18} }, // assignment 
    { {     316}, { 19} }, // write      
    { {     317}, { 20} }, // read       
    { {     318}, { 21} }, // while_loop 
    { {     319}, { 22} }, // for_loop   
    { {     320}, { 23} }, // conditional
    { {     259}, { 24} }, // SKIP       
    { {     282}, { 25} }, // IDENTIFIER 
    { {     277}, { 26} }, // WRITE      
    { {     276}, { 27} }, // READ       
    { {     270}, { 28} }, // WHILE      
    { {     271}, { 29} }, // FOR        
    { {     266}, { 30} }, // IF         
    { {       0}, { -9} },               
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_23[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       281}, { 35} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       280}, { 36} }, // ASSIGN
    { {         0}, {  0} },          
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       278}, { 37} }, // LEFT_BRACKET
    { {         0}, {  0} },                
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       278}, { 38} }, // LEFT_BRACKET
    { {         0}, {  0} },                
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 39} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       282}, { 46} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 47} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_31[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 48} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 49} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       282}, { 50} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       274}, { 51} }, // DO          
    { {       286}, { 52} }, // EQUALS      
    { {       284}, { 53} }, // AND         
    { {       285}, { 54} }, // OR          
    { {       287}, { 55} }, // LESS_THAN   
    { {       288}, { 56} }, // GREATER_THAN
    { {       289}, { 57} }, // PLUS        
    { {       290}, { 58} }, // MINUS       
    { {       291}, { 59} }, // ASTERIKS    
    { {       293}, { 60} }, // MOD         
    { {       292}, { 61} }, // DIV         
    { {         0}, {  0} },                
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 62} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 63} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       272}, { 64} }, // IN
    { {         0}, {  0} },      
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       267}, { 65} }, // THEN        
    { {       286}, { 52} }, // EQUALS      
    { {       284}, { 53} }, // AND         
    { {       285}, { 54} }, // OR          
    { {       287}, { 55} }, // LESS_THAN   
    { {       288}, { 56} }, // GREATER_THAN
    { {       289}, { 57} }, // PLUS        
    { {       290}, { 58} }, // MINUS       
    { {       291}, { 59} }, // ASTERIKS    
    { {       293}, { 60} }, // MOD         
    { {       292}, { 61} }, // DIV         
    { {         0}, {  0} },                
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       281}, { 66} }, // SEMICOLON   
    { {       286}, { 52} }, // EQUALS      
    { {       284}, { 53} }, // AND         
    { {       285}, { 54} }, // OR          
    { {       287}, { 55} }, // LESS_THAN   
    { {       288}, { 56} }, // GREATER_THAN
    { {       289}, { 57} }, // PLUS        
    { {       290}, { 58} }, // MINUS       
    { {       291}, { 59} }, // ASTERIKS    
    { {       293}, { 60} }, // MOD         
    { {       292}, { 61} }, // DIV         
    { {         0}, {  0} },                
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, { 12} },                 
    { {       279}, { 67} }, // RIGHT_BRACKET
    { {       286}, { 52} }, // EQUALS       
    { {       284}, { 53} }, // AND          
    { {       285}, { 54} }, // OR           
    { {       287}, { 55} }, // LESS_THAN    
    { {       288}, { 56} }, // GREATER_THAN 
    { {       289}, { 57} }, // PLUS         
    { {       290}, { 58} }, // MINUS        
    { {       291}, { 59} }, // ASTERIKS     
    { {       293}, { 60} }, // MOD          
    { {       292}, { 61} }, // DIV          
    { {         0}, {  0} },                 
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  2} },                 
    { {       279}, { 68} }, // RIGHT_BRACKET
    { {         0}, {  0} },                 
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, { 17} },               
    { {       312}, { 69} }, // statements 
    { {       313}, { 16} }, // statement  
    { {       314}, { 17} }, // skip       
    { {       315}, { 18} }, // assignment 
    { {       316}, { 19} }, // write      
    { {       317}, { 20} }, // read       
    { {       318}, { 21} }, // while_loop 
    { {       319}, { 22} }, // for_loop   
    { {       320}, { 23} }, // conditional
    { {       259}, { 24} }, // SKIP       
    { {       282}, { 25} }, // IDENTIFIER 
    { {       277}, { 26} }, // WRITE      
    { {       276}, { 27} }, // READ       
    { {       270}, { 28} }, // WHILE      
    { {       271}, { 29} }, // FOR        
    { {       266}, { 30} }, // IF         
    { {         0}, {  0} },               
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 70} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 71} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 72} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 73} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 74} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 75} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 76} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 77} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 78} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 79} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, { 12} },                 
    { {       279}, { 80} }, // RIGHT_BRACKET
    { {       286}, { 52} }, // EQUALS       
    { {       284}, { 53} }, // AND          
    { {       285}, { 54} }, // OR           
    { {       287}, { 55} }, // LESS_THAN    
    { {       288}, { 56} }, // GREATER_THAN 
    { {       289}, { 57} }, // PLUS         
    { {       290}, { 58} }, // MINUS        
    { {       291}, { 59} }, // ASTERIKS     
    { {       293}, { 60} }, // MOD          
    { {       292}, { 61} }, // DIV          
    { {         0}, {  0} },                 
};

SR__ s_63[] =
{
    { { REQ_DEF}, {  11} },                
    { {     286}, {  52} }, // EQUALS      
    { {     284}, {  53} }, // AND         
    { {     285}, {  54} }, // OR          
    { {     287}, {  55} }, // LESS_THAN   
    { {     288}, {  56} }, // GREATER_THAN
    { {     289}, {  57} }, // PLUS        
    { {     290}, {  58} }, // MINUS       
    { {     291}, {  59} }, // ASTERIKS    
    { {     293}, {  60} }, // MOD         
    { {     292}, {  61} }, // DIV         
    { {       0}, { -32} },                
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 81} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, { 17} },               
    { {       312}, { 82} }, // statements 
    { {       313}, { 16} }, // statement  
    { {       314}, { 17} }, // skip       
    { {       315}, { 18} }, // assignment 
    { {       316}, { 19} }, // write      
    { {       317}, { 20} }, // read       
    { {       318}, { 21} }, // while_loop 
    { {       319}, { 22} }, // for_loop   
    { {       320}, { 23} }, // conditional
    { {       259}, { 24} }, // SKIP       
    { {       282}, { 25} }, // IDENTIFIER 
    { {       277}, { 26} }, // WRITE      
    { {       276}, { 27} }, // READ       
    { {       270}, { 28} }, // WHILE      
    { {       271}, { 29} }, // FOR        
    { {       266}, { 30} }, // IF         
    { {         0}, {  0} },               
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       281}, { 83} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       281}, { 84} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       275}, { 85} }, // DONE
    { {         0}, {  0} },        
};

SR__ s_70[] =
{
    { { REQ_DEF}, {   8} },                
    { {     287}, {  55} }, // LESS_THAN   
    { {     288}, {  56} }, // GREATER_THAN
    { {     289}, {  57} }, // PLUS        
    { {     290}, {  58} }, // MINUS       
    { {     291}, {  59} }, // ASTERIKS    
    { {     293}, {  60} }, // MOD         
    { {     292}, {  61} }, // DIV         
    { {       0}, { -30} },                
};

SR__ s_71[] =
{
    { { REQ_DEF}, {   9} },                
    { {     286}, {  52} }, // EQUALS      
    { {     287}, {  55} }, // LESS_THAN   
    { {     288}, {  56} }, // GREATER_THAN
    { {     289}, {  57} }, // PLUS        
    { {     290}, {  58} }, // MINUS       
    { {     291}, {  59} }, // ASTERIKS    
    { {     293}, {  60} }, // MOD         
    { {     292}, {  61} }, // DIV         
    { {       0}, { -33} },                
};

SR__ s_72[] =
{
    { { REQ_DEF}, {   9} },                
    { {     286}, {  52} }, // EQUALS      
    { {     287}, {  55} }, // LESS_THAN   
    { {     288}, {  56} }, // GREATER_THAN
    { {     289}, {  57} }, // PLUS        
    { {     290}, {  58} }, // MINUS       
    { {     291}, {  59} }, // ASTERIKS    
    { {     293}, {  60} }, // MOD         
    { {     292}, {  61} }, // DIV         
    { {       0}, { -34} },                
};

SR__ s_73[] =
{
    { { REQ_DEF}, {   6} },            
    { {     289}, {  57} }, // PLUS    
    { {     290}, {  58} }, // MINUS   
    { {     291}, {  59} }, // ASTERIKS
    { {     293}, {  60} }, // MOD     
    { {     292}, {  61} }, // DIV     
    { {       0}, { -35} },            
};

SR__ s_74[] =
{
    { { REQ_DEF}, {   6} },            
    { {     289}, {  57} }, // PLUS    
    { {     290}, {  58} }, // MINUS   
    { {     291}, {  59} }, // ASTERIKS
    { {     293}, {  60} }, // MOD     
    { {     292}, {  61} }, // DIV     
    { {       0}, { -36} },            
};

SR__ s_75[] =
{
    { { REQ_DEF}, {   4} },            
    { {     291}, {  59} }, // ASTERIKS
    { {     293}, {  60} }, // MOD     
    { {     292}, {  61} }, // DIV     
    { {       0}, { -37} },            
};

SR__ s_76[] =
{
    { { REQ_DEF}, {   4} },            
    { {     291}, {  59} }, // ASTERIKS
    { {     293}, {  60} }, // MOD     
    { {     292}, {  61} }, // DIV     
    { {       0}, { -38} },            
};

SR__ s_77[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_78[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_79[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       273}, { 86} }, // RANGE       
    { {       286}, { 52} }, // EQUALS      
    { {       284}, { 53} }, // AND         
    { {       285}, { 54} }, // OR          
    { {       287}, { 55} }, // LESS_THAN   
    { {       288}, { 56} }, // GREATER_THAN
    { {       289}, { 57} }, // PLUS        
    { {       290}, { 58} }, // MINUS       
    { {       291}, { 59} }, // ASTERIKS    
    { {       293}, { 60} }, // MOD         
    { {       292}, { 61} }, // DIV         
    { {         0}, {  0} },                
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  3} },         
    { {       269}, { 87} }, // ENDIF
    { {       268}, { 88} }, // ELSE 
    { {         0}, {  0} },         
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {  8} },                   
    { {       321}, { 89} }, // expr           
    { {       263}, { 40} }, // TRUE           
    { {       264}, { 41} }, // FALSE          
    { {       283}, { 42} }, // NATURAL_LITERAL
    { {       282}, { 43} }, // IDENTIFIER     
    { {       278}, { 44} }, // LEFT_BRACKET   
    { {       265}, { 45} }, // NOT            
    { {         0}, {  0} },                   
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, { 17} },               
    { {       312}, { 90} }, // statements 
    { {       313}, { 16} }, // statement  
    { {       314}, { 17} }, // skip       
    { {       315}, { 18} }, // assignment 
    { {       316}, { 19} }, // write      
    { {       317}, { 20} }, // read       
    { {       318}, { 21} }, // while_loop 
    { {       319}, { 22} }, // for_loop   
    { {       320}, { 23} }, // conditional
    { {       259}, { 24} }, // SKIP       
    { {       282}, { 25} }, // IDENTIFIER 
    { {       277}, { 26} }, // WRITE      
    { {       276}, { 27} }, // READ       
    { {       270}, { 28} }, // WHILE      
    { {       271}, { 29} }, // FOR        
    { {       266}, { 30} }, // IF         
    { {         0}, {  0} },               
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, { 12} },                
    { {       274}, { 91} }, // DO          
    { {       286}, { 52} }, // EQUALS      
    { {       284}, { 53} }, // AND         
    { {       285}, { 54} }, // OR          
    { {       287}, { 55} }, // LESS_THAN   
    { {       288}, { 56} }, // GREATER_THAN
    { {       289}, { 57} }, // PLUS        
    { {       290}, { 58} }, // MINUS       
    { {       291}, { 59} }, // ASTERIKS    
    { {       293}, { 60} }, // MOD         
    { {       292}, { 61} }, // DIV         
    { {         0}, {  0} },                
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       269}, { 92} }, // ENDIF
    { {         0}, {  0} },         
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, { 17} },               
    { {       312}, { 93} }, // statements 
    { {       313}, { 16} }, // statement  
    { {       314}, { 17} }, // skip       
    { {       315}, { 18} }, // assignment 
    { {       316}, { 19} }, // write      
    { {       317}, { 20} }, // read       
    { {       318}, { 21} }, // while_loop 
    { {       319}, { 22} }, // for_loop   
    { {       320}, { 23} }, // conditional
    { {       259}, { 24} }, // SKIP       
    { {       282}, { 25} }, // IDENTIFIER 
    { {       277}, { 26} }, // WRITE      
    { {       276}, { 27} }, // READ       
    { {       270}, { 28} }, // WHILE      
    { {       271}, { 29} }, // FOR        
    { {       266}, { 30} }, // IF         
    { {         0}, {  0} },               
};

SR__ s_92[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       275}, { 94} }, // DONE
    { {         0}, {  0} },        
};

SR__ s_94[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 37 "while.y"
        {
         std::string code =
         std::string(
         "extern be_egesz\n") + 
         "extern be_logikai\n" + 
         "extern ki_egesz\n" + 
         "extern ki_logikai\n" + 
         "global main\n" + 
         "section .bss\n";
         for(symbol_table::iterator it = symbols.begin(); it != symbols.end(); ++it) {
         code += "    " + it->first + ": resb " + it->second.size() + "\n";
         }
         code += std::string("section .text\n") +
         "main:\n";
         code += *d_vsp__[0].text;
         std::cout << code << std::endl;
         delete d_vsp__[0].text;
         }
        break;

        case 2:
#line 58 "while.y"
        {
         d_val__.text = d_vsp__[0].text;
         }
        break;

        case 3:
#line 64 "while.y"
        {
         
         }
        break;

        case 4:
#line 71 "while.y"
        {
         
         }
        break;

        case 5:
#line 75 "while.y"
        {
         
         }
        break;

        case 6:
#line 82 "while.y"
        {
         insertSymbol(natural, *d_vsp__[-1].text);
         }
        break;

        case 7:
#line 86 "while.y"
        {
         insertSymbol(boolean, *d_vsp__[-1].text);
         }
        break;

        case 8:
#line 92 "while.y"
        {
         d_val__.text = d_vsp__[-1].text;
         }
        break;

        case 9:
#line 99 "while.y"
        {
         d_val__.text = new std::string(d_vsp__[0].op->code);
         delete d_vsp__[0].op;
         }
        break;

        case 10:
#line 104 "while.y"
        {
         d_val__.text = new std::string (d_vsp__[-1].op->code + *d_vsp__[0].text);
         delete d_vsp__[-1].op;
         delete d_vsp__[0].text;
         }
        break;

        case 11:
#line 113 "while.y"
        {
         d_val__.op = d_vsp__[0].op;
         }
        break;

        case 12:
#line 117 "while.y"
        {
         d_val__.op = d_vsp__[0].op;
         }
        break;

        case 13:
#line 121 "while.y"
        {
         d_val__.op = d_vsp__[0].op;
         }
        break;

        case 14:
#line 125 "while.y"
        {
         d_val__.op = d_vsp__[0].op;
         }
        break;

        case 15:
#line 129 "while.y"
        {
         d_val__.op = d_vsp__[0].op;
         }
        break;

        case 16:
#line 133 "while.y"
        {
         d_val__.op = d_vsp__[0].op;
         }
        break;

        case 17:
#line 137 "while.y"
        {
         d_val__.op = d_vsp__[0].op;
         }
        break;

        case 18:
#line 143 "while.y"
        {
         d_val__.op = new op_desc(LINE, "    nop\n");
         }
        break;

        case 19:
#line 149 "while.y"
        {
         symbol_table::iterator it = symbols.find(*d_vsp__[-3].text);
         if(it != symbols.end()) {
         assertType(":=", it->second.var_type, it->second.var_type, it->second.var_type, d_vsp__[-1].expr->expr_type);
         d_val__.op = new op_desc(LINE, d_vsp__[-1].expr->code + "    mov [" + *d_vsp__[-3].text +"], " + registers::a(size_of(d_vsp__[-1].expr->expr_type)) + "\n");
         } else {
         error_undeclared(*d_vsp__[-3].text);
         }
         delete d_vsp__[-3].text;
         delete d_vsp__[-1].expr;
         }
        break;

        case 20:
#line 163 "while.y"
        {
         d_val__.op = new op_desc(
         LINE,
         d_vsp__[-2].expr->code +
         "    push eax\n" +
         "    call " + (d_vsp__[-2].expr->expr_type == natural ? "ki_egesz" : "ki_logikai") + "\n" +
         "    add esp, 4\n"
         );
         delete d_vsp__[-2].expr;
         }
        break;

        case 21:
#line 176 "while.y"
        {
         symbol_table::iterator it = symbols.find(*d_vsp__[-2].text);
         if(it != symbols.end()) {
         d_val__.op = new op_desc(
         LINE,
         std::string("    call ") + (it->second.var_type == natural ? "be_egesz" : "be_logikai") + "\n" +
         "    mov [" + *d_vsp__[-2].text + "], " + registers::a(size_of(it->second.var_type)) + "\n"
         );
         } else {
         error_undeclared(*d_vsp__[-2].text);
         }
         delete d_vsp__[-2].text;
         }
        break;

        case 22:
#line 192 "while.y"
        {
         assertType("condition of while loop", boolean, d_vsp__[-3].expr->expr_type);
         std::string label_postfix = label::get_new();
         std::string start_label = std::string("while_start_") + label_postfix;
         std::string end_label = std::string("while_end_") + label_postfix;
         d_val__.op = new op_desc(
         LINE,
         start_label + ":\n" +
         d_vsp__[-3].expr->code +
         "    cmp al, 1\n" +
         "    jne near " + end_label + "\n" +
         *d_vsp__[-1].text +
         "    jmp near " + start_label + "\n" +
         end_label + ":\n"
         );
         delete d_vsp__[-3].expr;
         delete d_vsp__[-1].text;
         }
        break;

        case 23:
#line 213 "while.y"
        {
         symbol_table::iterator it = symbols.find(*d_vsp__[-7].text);
         if(it != symbols.end()) {
         assertType("for loop variable", natural, it->second.var_type);
         assertType("..", natural, natural, d_vsp__[-5].expr->expr_type, d_vsp__[-3].expr->expr_type);
         
         std::string label_postfix = label::get_new();
         std::string start_label = std::string("for_start_") + label_postfix;
         std::string end_label = std::string("for_end_") + label_postfix;
         std::string a = registers::a(size_of(d_vsp__[-5].expr->expr_type));
         std::string d = registers::d(size_of(d_vsp__[-5].expr->expr_type));
         d_val__.op = new op_desc(
         LINE,
         std::string(";for loop from here\n") +
         d_vsp__[-5].expr->code + 
         "    mov [" + *d_vsp__[-7].text + "], " + a + "\n" +
         d_vsp__[-3].expr->code +
         "    push eax\n" +
         start_label + ":\n" +
         "    pop edx\n" +
         "    mov " + a + ", [" + *d_vsp__[-7].text + "]\n" +
         "    cmp " + a + ", " + d + "\n" +
         "    ja " + end_label + "\n" +
         "    push edx\n" +
         *d_vsp__[-1].text + 
         "    inc " + asm_size(d_vsp__[-5].expr->expr_type) + " [" + *d_vsp__[-7].text + "]\n" +
         "    jmp " + start_label + "\n" +
         end_label + ":\n"
         );
         } else {
         error_undeclared(*d_vsp__[-7].text);
         }
         delete d_vsp__[-7].text;
         delete d_vsp__[-5].expr;
         delete d_vsp__[-3].expr;
         }
        break;

        case 24:
#line 253 "while.y"
        {
         assertType("condition of if statement", boolean, d_vsp__[-3].expr->expr_type);
         d_val__.op = new op_desc(
         LINE,
         ""
         );
         }
        break;

        case 25:
#line 261 "while.y"
        {
         assertType("condition of if statement", boolean, d_vsp__[-5].expr->expr_type);
         d_val__.op = new op_desc(
         LINE,
         ""
         );
         }
        break;

        case 26:
#line 272 "while.y"
        {
         d_val__.expr = new expr_desc(LINE, boolean, "    mov al, byte 1\n");
         }
        break;

        case 27:
#line 276 "while.y"
        {
         d_val__.expr = new expr_desc(LINE, boolean, "    mov al, byte 0\n");
         }
        break;

        case 28:
#line 280 "while.y"
        {
         d_val__.expr = new expr_desc(LINE, natural, std::string("    mov eax, ") + *d_vsp__[0].text + "\n");
         delete d_vsp__[0].text;
         }
        break;

        case 29:
#line 285 "while.y"
        {
         if(symbols.count(*d_vsp__[0].text) != 0) {
         d_val__.expr = new expr_desc(LINE, symbols[*d_vsp__[0].text].var_type, std::string("    mov ") + registers::a(size_of(symbols[*d_vsp__[0].text].var_type)) + ", [" + *d_vsp__[0].text + "]\n");
         } else {
         error_undeclared(*d_vsp__[0].text);
         }
         delete d_vsp__[0].text;
         }
        break;

        case 30:
#line 294 "while.y"
        {
         if(assertType("=", d_vsp__[-2].expr->expr_type, d_vsp__[-2].expr->expr_type, d_vsp__[-2].expr->expr_type, d_vsp__[0].expr->expr_type)) {
         d_val__.expr = new expr_desc(
         LINE,
         boolean, 
         two_param_compare(d_vsp__[-2].expr, d_vsp__[0].expr, "sete")
         );
         }
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 31:
#line 306 "while.y"
        {
         d_val__.expr = d_vsp__[-1].expr;
         }
        break;

        case 32:
#line 310 "while.y"
        {
         assertType("not", boolean, d_vsp__[0].expr->expr_type);
         d_val__.expr = new expr_desc(LINE, boolean, d_vsp__[0].expr->code + "    xor al, 1\n");
         delete d_vsp__[0].expr;
         }
        break;

        case 33:
#line 316 "while.y"
        {
         assertType("and", boolean, boolean, d_vsp__[-2].expr->expr_type, d_vsp__[0].expr->expr_type);
         d_val__.expr = new expr_desc(
         LINE,
         boolean,
         two_param_expr(d_vsp__[-2].expr, d_vsp__[0].expr, "and al, bl")
         );
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 34:
#line 327 "while.y"
        {
         assertType("or", boolean, boolean, d_vsp__[-2].expr->expr_type, d_vsp__[0].expr->expr_type);
         d_val__.expr = new expr_desc(
         LINE,
         boolean,
         two_param_expr(d_vsp__[-2].expr, d_vsp__[0].expr, "or al, bl")
         );
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 35:
#line 338 "while.y"
        {
         assertType("<", natural, natural, d_vsp__[-2].expr->expr_type, d_vsp__[0].expr->expr_type);
         d_val__.expr = new expr_desc(
         LINE,
         boolean, 
         two_param_compare(d_vsp__[-2].expr, d_vsp__[0].expr, "setb")
         );
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 36:
#line 349 "while.y"
        {
         assertType(">", natural, natural, d_vsp__[-2].expr->expr_type, d_vsp__[0].expr->expr_type);
         d_val__.expr = new expr_desc(
         LINE,
         boolean, 
         two_param_compare(d_vsp__[-2].expr, d_vsp__[0].expr, "seta")
         );
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 37:
#line 360 "while.y"
        {
         assertType("+", natural, natural, d_vsp__[-2].expr->expr_type, d_vsp__[0].expr->expr_type);
         d_val__.expr = new expr_desc(
         LINE,
         natural,
         two_param_expr(d_vsp__[-2].expr, d_vsp__[0].expr, "add eax, ebx")
         );
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 38:
#line 371 "while.y"
        {
         assertType("-", natural, natural, d_vsp__[-2].expr->expr_type, d_vsp__[0].expr->expr_type);
         d_val__.expr = new expr_desc(
         LINE,
         natural,
         two_param_expr(d_vsp__[-2].expr, d_vsp__[0].expr, "sub eax, ebx")
         );
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 39:
#line 382 "while.y"
        {
         assertType("*", natural, natural, d_vsp__[-2].expr->expr_type, d_vsp__[0].expr->expr_type);
         d_val__.expr = new expr_desc(
         LINE,
         natural,
         two_param_expr(d_vsp__[-2].expr, d_vsp__[0].expr, "mul ebx")
         );
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 40:
#line 393 "while.y"
        {
         assertType("mod", natural, natural, d_vsp__[-2].expr->expr_type, d_vsp__[0].expr->expr_type);
         d_val__.expr = new expr_desc(
         LINE,
         natural,
         two_param_expr(
         d_vsp__[-2].expr,
         d_vsp__[0].expr,
         std::string("xor edx, edx\n") + 
         "    div ebx\n" + 
         "    mov eax, edx"
         )
         );
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

        case 41:
#line 410 "while.y"
        {
         assertType("div", natural, natural, d_vsp__[-2].expr->expr_type, d_vsp__[0].expr->expr_type);
         d_val__.expr = new expr_desc(
         LINE,
         natural,
         two_param_expr(
         d_vsp__[-2].expr,
         d_vsp__[0].expr,
         std::string("xor edx, edx\n") + 
         "    div ebx"
         )
         );
         delete d_vsp__[-2].expr;
         delete d_vsp__[0].expr;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



